server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: file-preview-service

# JodConverter??
jodconverter:
  local:
    enabled: true
    office-home: "C:/Program Files/LibreOffice"
    port-numbers: 2002
    process-timeout: 120000
    process-restart-interval: 150000
    max-tasks-per-process: 10

# ?????
preview:
  output-dir: "./previews"
  image-format: "png"
  image-width: 800
  image-height: 600
  dpi: 150

# ????
logging:
  level:
    org.jodconverter: DEBUG
    com.example: DEBUG